import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { SafeAreaView } from 'react-native-safe-area-context';

import { calculateCalorieRange, type GoalValues } from '@/domain/goals/goalCalculator';
import { useAppDatabase } from '@/hooks/useAppDatabase';
import { GoalService } from '@/services/goals/goalService';
import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';
export default function ToleranceScreen() {
  const database = useAppDatabase(); const service = useMemo(() => new GoalService(database), [database]); const router = useRouter(); const [goal, setGoal] = useState<GoalValues | null>(null); const [percent, setPercent] = useState(10); const [busy, setBusy] = useState(false);
  useEffect(() => { service.loadToday().then((value) => { setGoal(value); setPercent(value.calorieTolerancePercent); }); }, [service]);
  const range = goal ? calculateCalorieRange(goal.calorieTarget, percent) : null;
  const save = async () => { if (!goal) return; setBusy(true); try { await service.saveToday({ ...goal, calorieTolerancePercent: percent }); router.back(); } catch (error) { Alert.alert('Could not save range', error instanceof Error ? error.message : 'Please try again.'); setBusy(false); } };
  return <SafeAreaView style={styles.safeArea}><View style={styles.header}><Pressable accessibilityLabel="Back" hitSlop={12} onPress={router.back}><SymbolView name="chevron.left" size={20} tintColor={colors.text} /></Pressable><Text style={styles.title}>CALORIE TARGET RANGE</Text><View style={styles.spacer} /></View><View style={styles.content}><Text style={styles.notice}>Changes take effect today. Previous days are not changed.</Text><View style={styles.stepper}><Pressable accessibilityLabel="Decrease tolerance" disabled={percent === 0} onPress={() => setPercent((value) => Math.max(0, value - 1))} style={styles.step}><Text style={styles.stepText}>−</Text></Pressable><Text style={styles.percent}>± {percent}%</Text><Pressable accessibilityLabel="Increase tolerance" disabled={percent === 100} onPress={() => setPercent((value) => Math.min(100, value + 1))} style={styles.step}><Text style={styles.stepText}>+</Text></Pressable></View>{goal && range ? <View style={styles.summary}><Text style={styles.summaryLabel}>Current calorie goal</Text><Text style={styles.summaryValue}>{goal.calorieTarget.toLocaleString()} kcal</Text><Text style={styles.summaryLabel}>Your target range</Text><Text style={styles.summaryValue}>{Math.round(range.lower).toLocaleString()} – {Math.round(range.upper).toLocaleString()} kcal</Text></View> : null}</View><View style={styles.action}><Pressable disabled={busy || !goal} onPress={save} style={[styles.button, (busy || !goal) && styles.dim]}><Text style={styles.buttonText}>{busy ? 'SAVING…' : 'SAVE'}</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safeArea: { backgroundColor: colors.background, flex: 1 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', padding: spacing.lg }, title: { color: colors.text, fontSize: 15, fontWeight: '800', letterSpacing: 0.7 }, spacer: { width: 20 }, content: { flex: 1, paddingHorizontal: spacing.screenHorizontal }, notice: { color: colors.textMuted, fontSize: 13, lineHeight: 19 }, stepper: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginVertical: spacing.xxl }, step: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, height: 54, justifyContent: 'center', width: 70 }, stepText: { color: colors.accent, fontSize: 28, fontWeight: '600' }, percent: { color: colors.text, fontSize: 25, fontWeight: '800' }, summary: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: spacing.xl }, summaryLabel: { color: colors.textMuted, fontSize: 13, marginTop: spacing.lg }, summaryValue: { color: colors.text, fontSize: 21, fontWeight: '700', marginTop: spacing.xs }, action: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, padding: spacing.md }, button: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 12, justifyContent: 'center', minHeight: 50 }, buttonText: { color: colors.surface, fontSize: 15, fontWeight: '800' }, dim: { opacity: 0.55 } });
